services:
  server:
    container_name : "system-api"
    build:
      context: ./
      dockerfile : Dockerfile
    environment:
      DATABASE_URL: "host=${POSTGRES_HOST} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} sslmode=disable"
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./:/app 
  postgres:
    container_name : "system-db"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports : 
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data 
volumes:
  pg-data: {} 

